defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

root_dir: '/home/sebalzer/Documents/Projects/AAOCASeg/data'
train: False

filters:
  plot: True
  nonlocal_means: 
    patch_size: 2
    patch_distance: 2
    h: 1
    fast_mode: True
    sigma: 0.0
    preserve_range: False