defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

dir_path: '/home/sebalzer/Documents/Projects/AAOCASeg/2_IVUSimages/RatnamNanthakumaran/20220406/082231/Run3/PD22JZCL'

filters:
  plot: True
  nonlocal_means: 
    patch_size: 2
    patch_distance: 2
    h: 1
    fast_mode: True
    sigma: 0.0
    preserve_range: False