defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

display:
  image_size: 1024
  windowing_sensitivity: 0.03  # 1 for default, below 1 for slower, above 1 for faster
  n_interactive_points: 10
  n_points_contour: 250
  contour_thickness: 3
  point_thickness: 1
  point_radius: 10

gating:
  min_window_size: 5
  max_window_size: 15
  step_size: 0.01

report:
  plot: False
  save_as_csv: False

save:
  autosave_interval: 10000  # in ms
  use_xml_files: False  # set True to use .xml files instead of .json to save contours, etc.
  # nifti_dir: '/home/sebalzer/Documents/Projects/AAOCASeg/niftis'
  nifti_dir: '/home/yungselm/Documents/niftis'
  save_niftis: 'none'  # 'contoured', 'all', 'none' (which frames to save as NIfTi)
  save_2d: False
  save_3d: True

segmentation:
  # model_file: '/home/sebalzer/Documents/Projects/AAOCASeg/models/u2net_2d_MINMAX_512_best.h5'
  model_file: '/home/yungselm/Documents/IVUS_models/u2net_2d_MINMAX_512_best.h5'
  batch_size: 16
  conserve_memory: True  # set to True for devices with less than 32 GB RAM (increases inference times)

filters:
  plot: True
  nonlocal_means: 
    patch_size: 2
    patch_distance: 2
    h: 1
    fast_mode: True
    sigma: 0.0
    preserve_range: False