defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

display:
  image_size: 800
  windowing_sensitivity: 0.03  # 1 for default, below 1 for slower, above 1 for faster
  spline_thickness: 3
  point_thickness: 1
  point_radius: 10

report:
  plot: True
  save_as_csv: True

save:
  autosave_interval: 10000  # in ms
  use_xml_files: False  # set True to use .xml files instead of .json to save contours, etc.
  nifti_dir: '/home/sebalzer/Documents/Projects/AAOCASeg/niftis'
  save_niftis: 'contoured'  # 'contoured', 'all', 'none' (which frames to save as NIfTi)
  save_2d: True
  save_3d: False

segmentation:
  train: False
  batch_size: 12
  num_workers: 24
  dropout_rate: 0.0
  learning_rate: 0.0001
  weight_decay: 0.00001
  max_epochs: 1000
  train_val_ratio: 0.8

filters:
  plot: True
  nonlocal_means: 
    patch_size: 2
    patch_distance: 2
    h: 1
    fast_mode: True
    sigma: 0.0
    preserve_range: False